const questionBank = [
  "I feel I am being paid a fair amount for the work I do.",
  "There is really too little chance for promotion on my job.",
  "My supervisor is quite competent in doing his/her job.",
  "I am not satisfied with the benefits I receive.",
  "When I do a good job, I receive the recognition for it that I should receive.",
  "Many of our rules and procedures make doing a good job difficult.",
  "I like the people I work with.",
  "I sometimes feel my job is meaningless.",
  "Communications seem good within this organization.",
  "Raises are too few and far between.",
  "Those who do well on the job stand a fair chance of being promoted.",
  "My supervisor is unfair to me.",
  "The benefits we receive are as good as most other organizations offer.",
  "I do not feel that the work I do is appreciated.",
  "My efforts to do a good job are seldom blocked by red tape.",
  "I find I have to work harder at my job because of the incompetence of people I work with.",
  "I like doing the things I do at work.",
  "The goals of this organization are not clear to me.",
  "I feel unappreciated by the organization when I think about what they pay me.",
  "People get ahead as fast here as they do in other places.",
  "My supervisor shows too little interest in the feelings of subordinates.",
  "The benefit package we have is equitable.",
  "There are few rewards for those who work here.",
  "I have too much to do at work.",
  "I enjoy my coworkers.",
  "I often feel that I do not know what is going on with the organization.",
  "I feel a sense of pride in doing my job.",
  "I feel satisfied with my chances for salary increases.",
  "There are benefits we do not have which we should have.",
  "I like my supervisor.",
  "I have too much paperwork.",
  "I don't feel my efforts are rewarded the way they should be.",
  "I am satisfied with my chances for promotion.",
  "There is too much bickering and fighting at work.",
  "My job is enjoyable.",
  "Work assignments are not fully explained."
];
